/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as UberUnsRouteImport } from './routes/uber-uns'
import { Route as ZahlungRouteImport } from './routes/zahlung'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const UberUnsRoute = UberUnsRouteImport.update({
  id: '/uber-uns',
  path: '/uber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const ZahlungRoute = ZahlungRouteImport.update({
  id: '/zahlung',
  path: '/zahlung',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/uber-uns': typeof UberUnsRoute
  '/zahlung': typeof ZahlungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/uber-uns': typeof UberUnsRoute
  '/zahlung': typeof ZahlungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/uber-uns': typeof UberUnsRoute
  '/zahlung': typeof ZahlungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontakt' | '/leistungen' | '/uber-uns' | '/zahlung'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/leistungen' | '/uber-uns' | '/zahlung'
  id: '__root__' | '/' | '/kontakt' | '/leistungen' | '/uber-uns' | '/zahlung'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  UberUnsRoute: typeof UberUnsRoute
  ZahlungRoute: typeof ZahlungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uber-uns': {
      id: '/uber-uns'
      path: '/uber-uns'
      fullPath: '/uber-uns'
      preLoaderRoute: typeof UberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zahlung': {
      id: '/zahlung'
      path: '/zahlung'
      fullPath: '/zahlung'
      preLoaderRoute: typeof ZahlungRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  UberUnsRoute: UberUnsRoute,
  ZahlungRoute: ZahlungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
